id: P006970
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3394
  title: བཅོམ་ལྡན་འདས་མའི་མན་ངག་གི་རྗེས་སུ་འབྲང་བ་ཞེས་བྱ་བའི་རྣམ་པར་བཤད་པ
  author: ''
  volumes:
    ea761866211f49c79c2ce4d6af6ce242:
      image_group_id: I1KG3467
      title: ''
      volume_number: 1
      total_pages: 1550
ebook_metadata:
  title: བཅོམ་ལྡན་འདས་མའི་མན་ངག་གི་རྗེས་སུ་འབྲང་བ་ཞེས་བྱ་བའི་རྣམ་པར་བཤད་པ
  author: ''
  sku: P006970
  cover: cover.jpg
  layers:
  - pagination
