id: P006970
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3394
  title: བཅོམ་ལྡན་འདས་མའི་མན་ངག་གི་རྗེས་སུ་འབྲང་བ་ཞེས་བྱ་བའི་རྣམ་པར་བཤད་པ
  author: ''
  volumes:
    f560e77efeee444bab6c82224064b1ab:
      image_group_id: I1KG3467
      title: Volume 1 of bcom ldan 'das ma'i man ngag gi rjes su 'brang ba zhes bya
        ba'i rnam par bshad pa
      volume_number: 1
      total_pages: 1550
      base_file: v001.txt
ebook_metadata:
  title: བཅོམ་ལྡན་འདས་མའི་མན་ངག་གི་རྗེས་སུ་འབྲང་བ་ཞེས་བྱ་བའི་རྣམ་པར་བཤད་པ
  author: ''
  sku: P006970
  cover: cover.jpg
  layers:
  - pagination
