id: I72EB26A8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:54:41+00:00'
last_modified: '2022-06-08T13:10:37.002672+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3394
  title: བཅོམ་ལྡན་འདས་མའི་མན་ངག་གི་རྗེས་སུ་འབྲང་བ་ཞེས་བྱ་བའི་རྣམ་པར་བཤད་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4EEC:
      image_group_id: I1KG3467
      title: Volume 1 of bcom ldan 'das ma'i man ngag gi rjes su 'brang ba zhes bya
        ba'i rnam par bshad pa
      total_pages: 1550
      order: 1
      base_file: 4EEC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
